services:
  frontend:
    # build:
      # context: .
      # dockerfile: Dockerfile
    image: ghcr.io/gueyeabdoulaye/cosf_front:pre-prod
    container_name: cosf-frontend
    ports:
      - "4200:80"
    environment:
      - VITE_APP_API_URL=https://api-staging.cosf.fr
      
