services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cosf-frontend
    ports:
      - "4200:80"
    environment:
      - VITE_APP_API_URL=http://pipi:8080/